name: CI

on:
  pull_request:
    branches:
      - master
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 180
    strategy:
      fail-fast: true
      matrix:
        java: [8, 11]
        os: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: 'Install & Java Test'
        run: bash ./mvnw clean install -DskipTests=false
#      - name: 'C++ Test'
#        run: bash ./cpp/build_and_test.sh
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          yml: ./codecov.yml
